### ISSUE TITLE
一些代码重复和闲置

### ISSUE THREAD

**Issue by songemeng** [zhangjikai/LinkGame#1]
最近仔细看了一下这个repository，似乎是几个人合作完成的。
但每个人的水平不太一致，而且各个部分的对接不是很完善。
比如刚才看到在DrawHelper.java中的 imageIDArray 也是初始化的作用。

**Comment by zhangjikai** [comment]
master 分支里的文件除了 Checker 类，其它的都是我写的，当时好像改过几版，有些地方确实写的不太好，仅供参考哈。
